---
# tasks file for roles/nginx

- name: Instal NGINX
  dnf:
    name: nginx
    state: present

- name: Pasang custom default landing page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'

- name: Pastikan NGINX berjalan dan otomatis aktif saat boot
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Buka port HTTP di Firewall (RHEL menggunakan firewalld)
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes