---
- name: Instal Node.js LTS
  dnf:
    name: nodejs
    state: present

- name: Buat direktori aplikasi
  file:
    path: /opt/express-app
    state: directory
    mode: '0755'

- name: Copy source code aplikasi
  copy:
    src: app.js
    dest: /opt/express-app/app.js

- name: Init npm dan install Express
  shell: |
    npm init -y
    npm install express
  args:
    chdir: /opt/express-app
    creates: /opt/express-app/package.json

- name: Buat systemd service unit
  copy:
    dest: /etc/systemd/system/express-app.service
    content: |
      [Unit]
      Description=ExpressJS Hello World App
      After=network.target

      [Service]
      Type=simple
      User=root
      WorkingDirectory=/opt/express-app
      ExecStart=/usr/bin/node app.js
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Jalankan service aplikasi
  systemd:
    name: express-app
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Izinkan Nginx untuk melakukan koneksi ke upstream (SELinux)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Pasang konfigurasi Nginx Proxy untuk Node.js
  template:
    src: nodejs_location.conf.j2
    dest: /etc/nginx/default.d/nodejs_app.conf # Perhatikan foldernya
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx